tplProjectName: mobilebuilder_tpl_7_9_0
â†“LoginComponent [mobile.components.UISharedComponent-1572604124714]: ğŸ— mobileSharedComponents/LoginComponent.yaml
â†“ForgotPassword [mobile.components.UISharedComponent-1582131761883]: ğŸ— mobileSharedComponents/ForgotPassword.yaml
â†“Page [mobile.components.PageComponent-1572604056200]: ğŸ— mobilePages/Page.yaml
â†“ModalPopup [mobile.components.PageComponent-1572623654326]: ğŸ— mobilePages/ModalPopup.yaml
â†“ForgotPasswordPage [mobile.components.PageComponent-1582131661217]: ğŸ— mobilePages/ForgotPasswordPage.yaml